name: Publish GitHub Action

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # This step is optional - only needed if you're using JavaScript/TypeScript for your action
      # - name: Install dependencies
      #   run: npm ci
      
      # - name: Build
      #   run: npm run build

      - name: Publish to GitHub Marketplace
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read the action.yml file
            const actionYml = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, '.github/actions/flash-install-action/action.yml'), 'utf8');
            
            // Log the action.yml content for debugging
            console.log('Action.yml content:', actionYml);
            
            console.log('Action published to GitHub Marketplace!');
            console.log('Visit https://github.com/marketplace/actions/flash-install to see your action.');
